### ISSUE TITLE
Unable to download data!  == "Folder is in Trash"

### ISSUE THREAD

**Issue by anilbatra2185** [zharry29/wikihow-goal-step#5]
Hi @zharry29 

Thank you for sharing the code/repo for your interesting work, however, it seems that data is missing now. I would appreciate if you restore the data or provide alternative to download the data.

![image](https://user-images.githubusercontent.com/7984207/114926604-77292e00-9e28-11eb-9829-5a14fe326d4b.png)

thanks

**Comment by zharry29** [comment]
Hi, thanks for your interest. All links are fixed.
